plataformacursos/clases/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('',ListarClases.as_view(), name="clases"),
    path('crear/',CreateClases.as_view(), name="createClases"),
    path('delete/<int:pk>/',EliminarClase.as_view(), name="eliminarClases"),
    path('modulo/crear/',CreateModulo.as_view(), name="createModulo"),
]

plataformacursos/pedidos/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('',login_required(ListarPedidos.as_view()), name="pedidos"),
    path('crear/',login_required(CreatePedidos.as_view()), name="createPedidos"),
    path('detalle/<int:pk>',login_required(DetallePedidos.as_view()), name="detallePedidos"),
    path('delete/<int:pk>',login_required(EliminarPedido.as_view()), name='deletePedidos'),
    path('mispedidos/<int:pk>',login_required(ListarMisPedidos.as_view()), name="misPedidos")
]

plataformacursos/plataformacursos/urls.py
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('cursos/', include('cursos.urls')),
    path('clases/', include('clases.urls')),
    path('recursos/', include('recursos.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('carrito/', include('carrito.urls')),
    path('pedidos/', include('pedidos.urls')),
    path("accounts/", include("django.contrib.auth.urls")), 
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)',serve,{
        'document_root': settings.MEDIA_ROOT,
    })
]

plataformacursos/pedidos/models.py
from django.db import models
from usuarios.models import *
from cursos.models import Cursos
from recursos.models import *

class Pedidos(models.Model):
    comprobante = models.FileField('comprobante', upload_to='comprobantes/',max_length=255,null=True, blank=True)
    total = models.DecimalField(max_digits=12,decimal_places=2,default=0.0)
    aprobado = models.BooleanField(default=False)
    alumno = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    fecha = models.DateField(default=datetime.today())

    def __str__(self):
        return str(self.id)

class DetallePedidosCursos(models.Model):
    alumno = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    pedido = models.ForeignKey(Pedidos, on_delete=models.CASCADE)
    curso = models.ForeignKey(Cursos, on_delete=models.CASCADE)
    aprobacion = models.BooleanField(default=False)

    def __str__(self):
        return self # TODO
    
class DetallePedidosRecursos(models.Model):
    alumno = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    pedido = models.ForeignKey(Pedidos, on_delete=models.CASCADE)
    recurso = models.ForeignKey(Recursos, on_delete=models.CASCADE)
    aprobacion = models.BooleanField(default=False)

    def __str__(self):
        return self # TODO

plataformacursos/pedidos/forms.py
from django.forms import *
from .models import *

class PedidosForm(ModelForm):
    class Meta:
        model = Pedidos
        fields = '__all__'

plataformacursos/pedidos/views.py
import json
from typing import Any, Dict
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render
from .models import *
from .forms import *
from django.urls import reverse_lazy,reverse
from django.views.generic import *

def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

class CreatePedidos(CreateView):
    model = Pedidos
    form_class = PedidosForm
    template_name = 'pedidos/create.html'
    success_url = reverse_lazy('index')

    def post(self, request, *args, **kwargs):
        data = {}
        if is_ajax(request=self.request):
            if request.POST['accion'] == 'guardar':
                try:
                    pedido = Pedidos()
                    pedido.comprobante = request.FILES['comprobante']
                    pedido.total = float(request.POST['total'])
                    pedido.alumno_id = int(request.POST['alumno'])
                    pedido.save()
                    cursos = json.loads(request.POST['cursos'])
                    for x in cursos:
                        detCurso = DetallePedidosCursos()
                        detCurso.pedido_id = pedido.id
                        detCurso.alumno_id = int(request.POST['alumno'])
                        detCurso.curso_id = int(x)
                        detCurso.save()
                    data['error'] = ''
                except Exception as e:
                    print(e)
                    data['error'] = str(e)
            if request.POST['accion'] == 'aprobar':
                try:
                    print(request.POST)
                    pedido = Pedidos.objects.get(id = int(request.POST['id']))
                    idAlumno = pedido.alumno.id
                    detallePCursos = DetallePedidosCursos.objects.filter(alumno_id = idAlumno).filter(pedido_id = pedido.id)
                    pedido.aprobado = True
                    pedido.save()
                    for detpcursos in detallePCursos:
                        detpcursos.aprobacion = True
                        detpcursos.save()
                        detcursos = DetallesCursos.objects.filter(curso_id = detpcursos.curso_id).filter(alumno_id = idAlumno)
                        for detcurso in detcursos:
                            detcurso.aprobacion = True
                            detcurso.save()
                    data['error']=''
                except Exception as e:
                    print(e)
                    data['error'] = str(e)
            
            return JsonResponse(data)

class ListarPedidos(ListView):
    model=Pedidos
    template_name = 'pedidos/index.html'
    context_object_name= 'pedidos'

class ListarMisPedidos(ListView):
    model=Pedidos
    template_name = 'pedidos/mispedidos.html'
    context_object_name= 'pedidos'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['pedidos'] = Pedidos.objects.filter(alumno_id=int(self.kwargs['pk']))
        return context

class DetallePedidos(DetailView):
    model = Pedidos
    template_name = 'pedidos/detalle.html'

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['cursos'] = DetallePedidosCursos.objects.filter(pedido_id = self.get_object().id)
        context['recursos'] = DetallePedidosRecursos.objects.filter(pedido_id = self.get_object().id)
        return context
    
class EliminarPedido(DeleteView):
    model = Pedidos
    template_name = 'delete/pedidos_delete.html'
    success_url= '../../pedidos'


    def delete(self, request, *args, **kwargs):
        if is_ajax(request=self.request):
            return reverse_lazy('pedidos')
        self.object = self.get_object()
        self.object.delete()
        mensaje = f'El pedido {self.model.id} eliminado correctamente'
        return JsonResponse({'mensaje': mensaje, 'error': ''})

plataformacursos/templates/pedidos/create.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block 'title' %}Crear{% endblock %}

{% block 'styles' %}
    <link rel="stylesheet" href="{% static 'css/pedidos/create.css' %}">
{% endblock %}


{% block 'content' %}
    <div class="mainContainer">
        <h1>Pagar pedido</h1>
        <div id="datosCuenta">
            <p>Para registrar su pago, realice un deposito o transferencia a las siguiente cuentas</p>
            <p>Luego suba su comprobante en formato PDF o imagen</p>
            <hr>
            <h3>Datos de la cuenta</h3>
            <hr>
            <img src="{% static 'img/datosCuenta.png' %}" alt="">
            <hr>
        </div>
        <form class="containerPedido" id="form_creacion" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <p><label for="">{{form.comprobante.label}}</label>{{form.comprobante}} </p>
            <p><label for="">{{form.total.label}}</label>{{form.total}} </p>
            <p style="display: none;">{{form.aprobado}} </p>
            <p style="display: none;">{{form.alumno}} </p>
            <p>{{form.errors}}</p>
        </form>
        <div id="button-container" class="buttonG">
            <input class="btn btn-success" id="añadir-usuario" type="submit" onclick="guardarPedido()" value="Pagar">
        </div> 
    </div> 
        
{% endblock 'content' %}


{% block script %}
    <script>
        const $select = document.querySelector('#id_alumno');
        const $valor = document.querySelector('#id_total');
        $select.value = '{{user.id}}'
        $valor.setAttribute('type','text')
        $valor.value = (parseFloat('{{carrito.getTotal}}')).toString()+'.00'
        const $listaCursos = []
        {% for item in carrito %}
            $listaCursos.push('{{item.curso.product.id}}')
        {% endfor %}
        console.log($listaCursos);
        $('#añadir-cliente').click(function(){
            mensajeSuccess('Cliente creado con exito')
        })
        const csrftoken = getCookie('csrftoken');
        function guardarPedido() {
            var data = new FormData($('#form_creacion').get(0))
            data.append("accion","guardar")
            data.append("cursos", JSON.stringify($listaCursos))
            $.ajax({
                url: "{% url 'createPedidos' %}",
                type: 'post',
                headers: {'X-CSRFToken': csrftoken},
                data: data,
                dataType: 'json',
                cache: false,
                contentType: false,
                processData: false,
            }).done(function(data){
                if (data['error'] == '') {
                    for (const key in $listaCursos) {
                        inscripcion(parseInt($listaCursos[key]),parseInt('{{user.id}}'));
                    }
                }else{
                    mensajeError(data['error'])
                }
            }).fail(function(data){
                mostrarErrores(data, 'producto');
            }).always(function(data){
                // alert("complete");
            });
        }
        function inscripcion(id,userId){
            var data = new FormData()
            data.append("id", id)
            data.append("user", userId)
            data.append("accion", 'inscripcionCurso')
            $.ajax({
                url: '{% url "createCursos" %}',
                type: 'post',
                headers: {'X-CSRFToken': csrftoken},
                data: data,
                dataType: 'json',
                cache: false,
                contentType: false,
                processData: false,
            }).done(function(data){
                if(data['error'] == ''){
                    mensajeSuccess('Recurso creado con exito')
                }else{
                    deleteC(id,'curso')
                    mensajeError(data['error']);
                }
            }).fail(function(data){
                mostrarErrores(data, 'producto');
            }).always(function(data){
                // alert("complete");
            });
        }
    </script>
{% endblock script %}
    

plataformacursos/templates/pedidos/detalle.html
{% load widget_tweaks %}

<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="exampleModalLabel">Pedido {{pedidos.id}} </h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div><label for="">Alumno: </label> {{pedidos.alumno.nombre}} {{pedidos.alumno.apellido}} </div>
            <div><label for="">Fecha: </label>{{pedidos.fecha}} </div>
            <div><label for="">Archivo: </label><a href="../media/{{pedidos.comprobante}}" target="_blank">{{pedidos.comprobante}}</a> </div>
            <div><label for="">Total: </label>$ {{pedidos.total}} </div>
            {% if cursos|length > 0 %}
                <hr>
                <div id="detalleCursos">
                    <h5>Cursos</h5>
                    <table id="tablaCursos">
                        <thead>
                            <th>Titulo</th>
                            <th>Precio</th>
                        </thead>
                        <tbody>
                            {% for curso in cursos %}
                                <tr>
                                    <td>{{curso.curso.titulo}}</td>
                                    <td>{{curso.curso.precio}} </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}
            
            {% if recursos|length > 0  %}
                <hr>
                <div id="detalleRecursos">
                    <h5>Recursos</h5>
                    <table id="tablaRecursos">
                        <thead>
                            <th>Titulo</th>
                            <th>Precio</th>
                        </thead>
                        <tbody>
                            {% for recurso in recursos %}
                                <tr>
                                    <td>{{recurso.recurso.titulo}}</td>
                                    <td>{{recurso.recurso.precio}} </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            <button type="button" class="btn btn-success" onclick="aprobar('{{pedido.id}}')">Aprobar</button>
        </div>
    </div>
</div>

<script>
    $('#tablaRecursos').DataTable();
    $('#tablaCursos').DataTable();
</script>

plataformacursos/templates/pedidos/index.html
{% extends '../base.html' %}
{% load static %}
{% block 'title' %}Crear{% endblock %}

{% block 'styles' %}
    <link rel="stylesheet" href="{% static 'css/pedidos/pedidos.css' %}">
{% endblock %}

{% block 'content' %}
    
    <div id="main-container">
        <h1>Lista de Pedidos</h1>
        <div class="buscador">
            <form class="search" action="{% url 'pedidos' %}" method="GET">
                <input class="search-bar" type="text" name="search" placeholder="Buscar pedidos...">
                <button class="btn btn-success" type="submit"><i class="bi bi-search"></i></button>
                <span class="aux-btns"><a class="btn btn-primary" href="{% url 'pedidos' %}">Ver todos</a> </span>
            </form>
        </div>
        
        <div><title></title></div>
        <table id="tablaPedidos">
            <thead>
                <tr id="table-title">
                    <th>#Orden</th>
                    <th>Cliente</th>
                    <th>Fecha</th>
                    <th>Total</th>
                    <th>Actuadores</th>
                </tr>
            </thead>
            <tbody>
                {% for pedido in pedidos %}
                <tr class="table-inf">
                    <td class="inf-id">{{ pedido.id }}</td>
                    <td class="inf-cliente">{{ pedido.alumno.nombre}} {{pedido.alumno.apellido}}</td>
                    <td class="inf-fecha">{{ pedido.fecha }}</td>
                    <td class="inf-total">$ {{ pedido.total }}</td>
                    <td class="botones">
                        <span>
                            <button class="btn btn-primary" type="button" onclick="abrir_modal('../pedidos/detalle/{{pedido.id}}')"><i class="bi bi-file-text"></i></button> 
                            {% if pedido.aprobado == False %}
                                <a class="btn btn-success" onclick="aprobar('{{pedido.pk}}')"><i class="bi bi-file-earmark-check"></i></a>
                            {% endif %}
                            <button class="btn btn-danger" type="button" onclick="abrir_modal('../pedidos/delete/{{pedido.id}}')"><i class="bi bi-trash"></i></button>                            
                        </span>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    
    <!-- The Modal -->
    <div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="addModalCategoria" aria-hidden="true" role="dialog">
    </div>
{% endblock 'content' %}


{% block script %}
    <script>
        $('#tablaPedidos').DataTable();
        $('#tablaRecursos').DataTable();
        $('#tablaCursos').DataTable();
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');
        function eliminar_pedido(pk){
            $.ajax({
                data:{
                    csrfmiddlewaretoken: $("[name = 'csrfmiddlewaretoken']").val()
                },
                url: '../pedidos/delete/'+pk,
                type: 'post',
            }).done(function(data){
                mensajeSuccess('El pedido ha sido eliminado con exito')
            }).fail(function(error){

            })
        }
        function aprobar(pk){
            $.ajax({
                url: "{% url 'createPedidos' %}",
                type: 'post',
                headers: {'X-CSRFToken': csrftoken},
                data:{
                    accion: 'aprobar',
                    id: pk
                },
                dataType: 'json',
            }).done(function(data){
                if (data['error'] == '') {
                    mensajeSuccess('El pedido ha sido aprobado con exito')
                }else{
                    mensajeError(data['error'])
                }
            }).fail(function(error){

            })
        }
    </script>    
{% endblock script %}
    

plataformacursos/templates/pedidos/mispedidos.html
{% extends '../base.html' %}
{% load static %}
{% block 'title' %}Crear{% endblock %}

{% block 'styles' %}
    <link rel="stylesheet" href="{% static 'css/pedidos/pedidos.css' %}">
{% endblock %}

{% block 'content' %}
    
    <div id="main-container">
        <h1>Mis Pedidos</h1>
        <div class="buscador">
            <form class="search" action="{% url 'pedidos' %}" method="GET">
                <input class="search-bar" type="text" name="search" placeholder="Buscar pedidos...">
                <button class="btn btn-success" type="submit"><i class="bi bi-search"></i></button>
                <span class="aux-btns"><a class="btn btn-primary" href="{% url 'pedidos' %}">Ver todos</a> </span>
            </form>
        </div>
        
        <div><title></title></div>
        {% if pedidos|length > 0 %}
            <table id="tablaPedidos">
                <thead>
                    <tr id="table-title">
                        <th>#Orden</th>
                        <th>Cliente</th>
                        <th>Fecha</th>
                        <th>Total</th>
                        <th>Actuadores</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pedido in pedidos %}
                    <tr class="table-inf">
                        <td class="inf-id">{{ pedido.id }}</td>
                        <td class="inf-cliente">{{ pedido.alumno.nombre}} {{pedido.alumno.apellido}}</td>
                        <td class="inf-fecha">{{ pedido.fecha }}</td>
                        <td class="inf-total">$ {{ pedido.total }}</td>
                        <td class="botones">
                            <span>
                                <button class="btn btn-primary" type="button" onclick="abrir_modal('../../pedidos/detalle/{{pedido.id}}')"><i class="bi bi-file-text"></i></button> 
                                <button class="btn btn-danger" type="button" onclick="abrir_modal_eliminacion('ordenes/delete/{{orden.id}}')"><i class="bi bi-trash"></i></button>                            
                            </span>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>
    
    <!-- The Modal -->
    <div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="addModalCategoria" aria-hidden="true" role="dialog">
    </div>
{% endblock 'content' %}


{% block script %}
    <script>
        $('#tablaPedidos').DataTable();
        $('#tablaRecursos').DataTable();
        $('#tablaCursos').DataTable();
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');
        function eliminar_orden(pk){
            $.ajax({
                data:{
                    csrfmiddlewaretoken: $("[name = 'csrfmiddlewaretoken']").val()
                },
                url: 'ordenes/delete/'+pk,
                type: 'post',
            }).done(function(data){
                if (data['error'] == '') {
                    cerrar_modal_eliminacion()
                    mensajeSuccess('La orden ha sido Eliminada con exito');
                }else{
                    mensajeError(data['error'])
                }
            }).fail(function(error){

            })
        }
        function aprobar(pk){
            $.ajax({
                url: "{% url 'createPedidos' %}",
                type: 'post',
                headers: {'X-CSRFToken': csrftoken},
                data:{
                    accion: 'aprobar',
                    id: pk
                },
                dataType: 'json',
            }).done(function(data){
                if (data['error'] == '') {
                    mensajeSuccess('La orden ha sido aprobada con exito')
                }else{
                    mensajeError(data['error'])
                }
            }).fail(function(error){

            })
        }
    </script>    
{% endblock script %}
    